name: StaffGui
version: '1.0-SNAPSHOT'
main: hu.shiya.staffGui.StaffGui
api-version: '1.21'
authors: [ Shiya ]
description: A Plugin that welcomes a newly joined player
commands:
  staff:
    description: Disable on Enable staff mode!
    usage: /staff
  staffitems:
    description: opens a gui where you can get staff helper items.
    usage: /staffitems